# Generated by Django 5.2.3 on 2025-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('secKey', models.IntegerField()),
                ('eMessage', models.CharField(max_length=1000)),
            ],
        ),
    ]
